### ISSUE TITLE
Request: Publish `no-fallthrough` rule as its own npm package 

### ISSUE THREAD

**Issue by binary64** [evelynhathaway/eslint-plugin-evelyn#108]
I would like to use `no-fallthrough` but am scared about the number of deps this package has.

**Comment by binary64** [comment]
Whoops, is this it: https://eslint.org/docs/rules/no-fallthrough ?

Or does yours have differences?

**Comment by evelynhathaway** [comment]
Totally fair! `no-fallthrough` from this package used to be a fork of the ESLint version that worked better with case blocks. Their stale bot closed and locked my pull request from a few years ago (https://github.com/eslint/eslint/pull/11016), and I added it to this package since I thought not many cared much about this edge case.

But now, **if you set up `eslint ^7.29.0` ([changelog](https://github.com/eslint/eslint/releases/tag/v7.29.0)), you should experience the same behavior as my version** since someone else implemented a similar fix. I am both thankful and salty that someone else got this fixed almost three years later haha!

I will be verifying the native version of `no-fallthrough` works the same as mine now and then remove it in the next major version.

**Comment by evelynhathaway** [comment]
I verified the native version of `no-fallthrough` from ESLint and it only fails one of the tests:

https://github.com/evelynhathaway/eslint-plugin-evelyn/blob/7ebae518a29f849fa9eae2767b1108c5447f4632/test/rules/fixes/no-fallthrough.js#L183-L186

This edge case is not one I am interested in preserving, so as planned, I will remove this in the next major version. Feel free to use the native version! 🚀
